apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-depl
    labels:
        app: auth-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: auth
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                - name: auth
                  image: auth
                  ports:
                      - containerPort: 8080
                        protocol: TCP
                  imagePullPolicy: Never
                  env:
                      - name: MONGO_URI
                        value: "mongodb://auth-mongo-srv:27017/auth"
                      - name: HTTP_SERVER_ADDRESS
                        value: "0.0.0.0:8080"
                      - name: TOKEN_SYMMETRIC_KEY
                        value: "SwszwLvpT5hKVNDwW7YJVEbLACOymVTQ"
                      - name: NATS_URL
                        value: 'nats://nats:4222'

---
apiVersion: v1
kind: Service
metadata:
    name: auth-srv
spec:
    selector:
        app: auth
    ports:
        - name: auth
          protocol: TCP
          port: 8080
          targetPort: 8080
