apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-depl
  labels:
    app: graph-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph
  template:
    metadata:
      labels:
        app: graph
    spec:
      containers:
        - name: graph
          image: graph
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Never
          env:
            - name: NEO4J_URI
              value: "neo4j://graph-neo4j-srv:7687/"
            - name: HTTP_SERVER_ADDRESS
              value: "0.0.0.0:8080"
            - name: TOKEN_SYMMETRIC_KEY
              value: "SwszwLvpT5hKVNDwW7YJVEbLACOymVTQ"
            - name: NATS_URL
              value: 'nats://nats:4222'

---
apiVersion: v1
kind: Service
metadata:
  name: graph-srv
spec:
  selector:
    app: graph
  ports:
    - name: graph
      protocol: TCP
      port: 8080
      targetPort: 8080
